version: '3.7'

services:
  app:
    build: .
    pull_policy: build
    container_name: nuxt-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NITRO_HOST=${NITRO_HOST}
      - NITRO_PORT=${NITRO_PORT}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    command: 'source <(printenv) &&node .//.output//server//index.mjs'
