version: '3.7'

services:
  app:
    build: .
    container_name: nuxt-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    command: 'node .//.output//server//index.mjs'
